Make a working docker-compose dev env
vhs/nomos pull request #297
Opened 2023-04-29 01:17 UTC by lf-

There were various issues in the docker-compose setup that made it unsuitable
for a development environment, and some things that plain didn't work. I've
fixed all of these up and got it working locally. I'm going to write
documentation for this on the wiki soon.

- fix(docker-compose): remove bad "external" property of networks
- fix(docker-compose.sh): load the env file, fix shellcheck
- feat(docker-compose): add self-contained dev configuration
- fix(docker-compose): load the environment into the webhooker service
- docs: update repo URL in README
- fix(docker-compose): make the mysql service actually work
- chore(webhooker): npm added name to the lockfile
- feat(setup): add a script to create an API key for the webhook service

2023-04-29 17:39 UTC, TyIsI requested changes

2023-04-29 17:58 UTC, lf- commented on docker-compose/core.network-proxy.yml
> -    external: true
Alright, I can fix that up, but it will result in having some duplication.

2023-04-30 03:43 UTC, lf- commented on docker-compose.sh
> +scriptdir=$(realpath "$(dirname "$0")")
My usual convention is uppercase if it's exported and lowercase if not. I can change it if you'd like.

2023-04-30 04:46 UTC, lf- commented on docker-compose/core.network-proxy.yml
> -    external: true
Fixed up, with aforementioned duplication.

2023-04-30 04:51 UTC, lf- commented on docker-compose.sh
> +scriptdir=$(realpath "$(dirname "$0")")
Changed.

2023-10-05 19:30 UTC, TyIsI approved these changes

2023-10-05 19:31 UTC, merged